### ISSUE TITLE
Support for cocoaDialog?

### ISSUE THREAD

**Issue by blackwood** [bcbernardo/aw-watcher-ask#5]
Hi, this looks like a great utility. I was wondering if you were planning on feature support in MacOS, mainly in using [cocoaDialog](https://github.com/cocoadialog/cocoadialog) to launch the modal?

**Comment by bcbernardo** [comment]
The watcher depends on zenity library, which is available for installation in MacOS using [homebrew](https://formulae.brew.sh/formula/zenity#default). Have you tried this option?

**Comment by blackwood** [comment]
Will try that, thanks!
